### ISSUE TITLE
The mechanism of drop the packet when queue?

### ISSUE THREAD

**Issue by bupt-steven** [SoonyangZhang/quic_simulator#1]
Thanks for your code. I have two questions for this simulator: 
1. I want to ask is there any code for dropping the tail packet when queue? As I know the switch or router have some algorithm like RED.
2. I want to the code is from WebRTC or chromium project? can you tell me the real path ?

**Comment by SoonyangZhang** [comment]
This code is extractd from quic project, for me to learn the working principle of net simulator. It only drops packets when the buffer in switch is fully ocupied. The origin code was appied to test the performance of quic by its authors, I gusss.  These code is still there in quic: https://cs.chromium.org/chromium/src/net/third_party/quiche/src/quic/test_tools/simulator. But not RED algorithms is impletment. For that, you could use TC or ns3.
